name: untitled4
description: A new Flutter project.
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies
  image_picker: ^0.8.7+3      # To pick images from the gallery or camera
  cupertino_icons: ^1.0.2     # iOS styled icons for Cupertino (iOS) design
  fluttertoast: ^8.2.2        # To show toast notifications
  webview_flutter: ^4.2.2     # For rendering web views
  dio: ^5.6.0                 # For network requests (HTTP client)
  get: ^4.6.1                 # State management, routing, and DI (GetX)
  uuid: ^3.0.7                # To generate unique IDs (UUID)

dev_dependencies:
  flutter_test:
    sdk: flutter              # Testing framework for Flutter
  flutter_lints: ^2.0.0       # Dart linter for maintaining code quality

flutter:
  uses-material-design: true

  assets:
    - assets/images/     # Path for image assets
